name: gs
version: 0.2.1
description: |-
  Provides Google Cloud Storage protocol support for chart downloading.
usage: |-
  The plugin allows to use Google Storage protocol to fetch charts.
  Requires 'gsutil' tool.
command: "$HELM_PLUGIN_DIR/bin/main.sh"
downloaders:
  - protocols: ["gs"]
    command: "bin/fetch.sh"
